version: '3'

services: 
  db:
    image: mysql:5.7
    container_name: 'database'
    restart: always
    volumes:
      - ./.db:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hurb
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 1

  app: 
    build: .
    command: ["./entrypoint.sh"]
    ports: 
      - '3000:3000'
    volumes: 
      - .:/usr/app
    depends_on:
      db:
        condition: service_healthy
